# Generated by Django 4.0.6 on 2022-08-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_alter_profile_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(max_length=1000)),
                ('drugusage', models.TextField(max_length=10000)),
                ('drugurl', models.URLField(max_length=500)),
            ],
        ),
    ]
