# Generated by Django 4.0.6 on 2022-08-08 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0010_alter_drug_drugusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(blank=True, max_length=1000, null=True)),
                ('treatment', models.TextField(blank=True, max_length=10000, null=True)),
                ('consultationdate', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Precription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(blank=True, null=True)),
                ('drugqty', models.IntegerField(blank=True, null=True)),
                ('patientrecordtime', models.DateTimeField(auto_now_add=True)),
                ('consultationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.consultation')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.drug')),
            ],
        ),
    ]
