# Generated by Django 4.0.6 on 2022-08-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0011_consultation_precription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precription',
            name='patientrecordtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
