# Generated by Django 4.0.6 on 2022-08-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0013_remove_precription_patientrecordtime_drugtakingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='symptom',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='treatment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
