# Generated by Django 4.0.6 on 2022-08-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0014_alter_consultation_symptom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugtakingtime',
            name='drugtakingdate',
            field=models.DateTimeField(),
        ),
    ]
