# Generated by Django 4.0.6 on 2022-08-12 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0015_alter_drugtakingtime_drugtakingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultationpatient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='precription',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precriptiondrug', to='medicines.drug'),
        ),
    ]
