# Generated by Django 4.0.6 on 2022-08-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0016_alter_consultation_patient_alter_precription_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugtakingtime',
            name='consultationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugtakingtimeconsultationid', to='medicines.consultation'),
        ),
    ]
