# Generated by Django 4.0.6 on 2022-08-16 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0017_alter_drugtakingtime_consultationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precription',
            name='consultationid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precriptionconsultationid', to='medicines.consultation'),
        ),
    ]
